[mypy]
python_version = 3.10
files = observer.py, state_server.py, state_client.py, checkpoint_registry.py, cfa.py, model.py, build_dataset.py, export_onnx.py, tests/test_training_state_ipc.py
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
check_untyped_defs = True
show_error_codes = True
pretty = True

[mypy-dashboard]
ignore_errors = True

[mypy-psutil]
ignore_missing_imports = True

[mypy-pynvml]
ignore_missing_imports = True

[mypy-onnxconverter_common]
ignore_missing_imports = True

[mypy-onnxruntime]
ignore_missing_imports = True
