import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import { writeFileAtomic, removeIfExists } from './atomic-write';
let dir: string; let target: string;
beforeEach(async () => { dir = await fs.mkdtemp(path.join(os.tmpdir(), 'xveon-atomic-')); target = path.join(dir, 'a.xmp'); await fs.writeFile(target, 'original'); });
afterEach(async () => { vi.restoreAllMocks(); await fs.rm(dir, { recursive: true, force: true }); });
it('replaces atomically in the same directory and removes idempotently', async () => { await writeFileAtomic(target, 'new'); expect(await fs.readFile(target, 'utf8')).toBe('new'); expect(await fs.readdir(dir)).toEqual(['a.xmp']); await removeIfExists(target); await removeIfExists(target); expect(await fs.readdir(dir)).toEqual([]); });
it('preserves the original and cleans temporary files after rename failure', async () => { vi.spyOn(fs, 'rename').mockRejectedValue(Object.assign(new Error('EIO: rename failed'), { code: 'EIO' })); await expect(writeFileAtomic(target, 'new')).rejects.toThrow('EIO: rename failed'); expect(await fs.readFile(target, 'utf8')).toBe('original'); expect(await fs.readdir(dir)).toEqual(['a.xmp']); });
it('retries EBUSY twice and eventually replaces the original', async () => { vi.spyOn(fs, 'rename').mockRejectedValueOnce(Object.assign(new Error('busy'), { code: 'EBUSY' })).mockRejectedValueOnce(Object.assign(new Error('busy'), { code: 'EBUSY' })); await writeFileAtomic(target, 'new', { renameRetries: [1, 1] }); expect(await fs.readFile(target, 'utf8')).toBe('new'); expect(await fs.readdir(dir)).toEqual(['a.xmp']); });
it('propagates ENOSPC from a partial write and cleans up', async () => { const write = fs.writeFile.bind(fs); vi.spyOn(fs, 'writeFile').mockImplementationOnce(async (...args) => { await write(args[0], 'partial'); throw Object.assign(new Error('ENOSPC: no space left on device'), { code: 'ENOSPC' }); }); await expect(writeFileAtomic(target, 'new')).rejects.toThrow('ENOSPC: no space left on device'); expect(await fs.readFile(target, 'utf8')).toBe('original'); expect(await fs.readdir(dir)).toEqual(['a.xmp']); });
